### ISSUE TITLE
BUG?? Dircolor not working in zsh and alacritty

### ISSUE THREAD

**Issue by Stratos-Crimson** [arcticicestudio/nord-dircolors#25]
Hello,
I am using alacritty with the nord colour pallete and zsh but it's not showing the nord colours in the ls command(it might also not be showing these in others but I have just tested it with ls) BUT it shows them in BASH for whatever reason.....
And yes, I have followed the instructions and put test -r "~/.dir_colors" && eval $(dircolors ~/.dir_colors) in my bash and zshrc as well as put the dir colors file in my home directory.

**Comment by jpasquier** [comment]
Hi,

I have the same problem with alacritty and zsh.

Best regards

**Comment by haroun** [comment]
I had the same issue and it has already been solved here https://github.com/arcticicestudio/nord-dircolors/pull/21/files

I don’t know why it was removed from the README file

> For `zsh`, color does not output to the terminal for `ls` unless `ls --color` is used. You can alias the `ls` command inside your `.zshrc` file with `alias ls='ls --color=auto'` to have `ls` output the colors for each session.

Credits to @szul

**Comment by Stratos-Crimson** [comment]
Thanks, but why the auto?
Also, I am still not getting syntax highlighting

**Comment by svengreb** [comment]
Please see my detailed explanation in https://github.com/arcticicestudio/nord-dircolors/pull/21#issuecomment-833014527 that describes how `dircolors` works and that it is not related to specific shells at all.

**Comment by haroun** [comment]
@svengreb thank you for the details. Sadly the `README.md` nor the [official installation & activation guide](https://www.nordtheme.com/docs/ports/dircolors/installation) mentions that.

Will it be OK if I open a PR with a link to the [official type support guide](https://www.nordtheme.com/docs/ports/dircolors/type-support)?

**Comment by svengreb** [comment]
@haroun PRs are always welcome, but like described in the linked comment this is simply out of scope for this project. I know that it might be hard to understand for users who are new to Unix/GNU/Linux tooling, but adding instructions and details about really each piece of the puzzle is absolutely exaggerated.

I'm running out of words to explain, but maybe imagine this: You searched and found a recipe you'd like to cook, but it does not contain a detailed guide how to use a fork nor how to use a steak knife and there are no information about [every single type of kitchen knife in as much detail as a Wikipedia article][1]. The scope of the recipe is to provide a list of required ingredients and the steps how to process them, but explaining such basics is absolutely out of scope.

This example can be reflected to the problem here: Users must know what `dircolors` is and that the `ls` commands are not bound to a specific shell at all but are simply basic **external** tool(s). Like you mentioned the page about the supported types also includes a information box at the top which basically shouldn't be part of the documentation either, but has been added to help at least to quickly get an idea how `dircolors` is working.

[1]: https://en.wikipedia.org/wiki/Kitchen_knife

**Comment by haroun** [comment]
@svengreb that's good enough for me. Thank you.

I'll let @Stratos-Crimson close the issue if he or she considers the initial problem solved.

**Comment by Stratos-Crimson** [comment]
Thank you :)
